name: Python CI

on:
  push:
    branches: [ "master" ] # master ブランチへの push 時に実行
  pull_request:
    branches: [ "master" ] # master ブランチへの pull request 時に実行

jobs:
  ci:
    runs-on: ubuntu-latest # Ubuntu の最新版ランナーを使用

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # コードをチェックアウト

    - name: Set up uv
      uses: astral-sh/setup-uv@v5 # uv をセットアップ
      with:
        enable-cache: true # uv のキャッシュを有効にする

    - name: Sync dependencies
      run: uv sync

    - name: Lint code
      run: uv run ruff check --quiet # リンターを実行

    - name: Check formatting
      run: uv run ruff format --check # フォーマットをチェック

    - name: Run tests
      run: uv run pytest # テストを実行